Get http://localhost:8080/test HTTP/1.1
Content-Type: application/json
API_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJibG9ja19kdXJhdGlvbiI6MzAwLCJleHAiOjE3NTQyNTE5NTIsInJhdGVfbGltaXQiOjEwLCJyYXRlX2xpbWl0X2R1cmF0aW9uIjo2MH0.YQ07rczvF9aOEsWnQplklj7k8Khlj5rr3nfNwjYhXTA